import type { KeyboardTheme } from "../types";

export const PRESET_THEMES: KeyboardTheme[] = [
	{
		id: "default",
		name: "Default",
		colors: {
			primary: "#0f172a",
			secondary: "#f8fafc",
			accent: "#0f172a",
			background: "#ffffff",
			foreground: "#000000",
			destructive: "#ef4444",
			text: "#ffffff",
		},
	},
	{
		id: "midnight",
		name: "Midnight Sky",
		colors: {
			primary: "#1e293b",
			secondary: "#334155",
			accent: "#6366f1",
			background: "#0f172a",
			foreground: "#f1f5f9",
			destructive: "#f87171",
			text: "#f1f5f9",
		},
	},
	{
		id: "sunset",
		name: "Sunset Glow",
		colors: {
			primary: "#d97706",
			secondary: "#fef3c7",
			accent: "#f97316",
			background: "#fffbeb",
			foreground: "#7c2d12",
			destructive: "#dc2626",
			text: "#7c2d12",
		},
	},
	{
		id: "ocean",
		name: "Ocean Wave",
		colors: {
			primary: "#0284c7",
			secondary: "#e0f2fe",
			accent: "#0ea5e9",
			background: "#f0f9ff",
			foreground: "#0c4a6e",
			destructive: "#dc2626",
			text: "#0c4a6e",
		},
	},
	{
		id: "forest",
		name: "Emerald Forest",
		colors: {
			primary: "#065f46",
			secondary: "#d1fae5",
			accent: "#10b981",
			background: "#f0fdf4",
			foreground: "#064e3b",
			destructive: "#dc2626",
			text: "#d1fae5",
		},
	},
	{
		id: "lavender",
		name: "Lavender Mist",
		colors: {
			primary: "#7c3aed",
			secondary: "#ede9fe",
			accent: "#c084fc",
			background: "#f8f5ff",
			foreground: "#312e81",
			destructive: "#f43f5e",
			text: "#f8f5ff",
		},
	},
	{
		id: "citrus",
		name: "Citrus Punch",
		colors: {
			primary: "#f59e0b",
			secondary: "#fef3c7",
			accent: "#fbbf24",
			background: "#fff7ed",
			foreground: "#78350f",
			destructive: "#b91c1c",
			text: "#78350f",
		},
	},
	{
		id: "rosewood",
		name: "Rosewood Bloom",
		colors: {
			primary: "#881337",
			secondary: "#fce7f3",
			accent: "#e11d48",
			background: "#fff1f2",
			foreground: "#4c0519",
			destructive: "#b91c1c",
			text: "#fff1f2",
		},
	},
	{
		id: "iceberg",
		name: "Iceberg Blue",
		colors: {
			primary: "#0ea5e9",
			secondary: "#e0f2fe",
			accent: "#3b82f6",
			background: "#f0f9ff",
			foreground: "#075985",
			destructive: "#ef4444",
			text: "#f0f9ff",
		},
	},
	{
		id: "candy",
		name: "Candy Floss",
		colors: {
			primary: "#ec4899",
			secondary: "#fce7f3",
			accent: "#f9a8d4",
			background: "#fff0f6",
			foreground: "#881337",
			destructive: "#b91c1c",
			text: "#fff0f6",
		},
	},
	{
		id: "autumn",
		name: "Autumn Spice",
		colors: {
			primary: "#b45309",
			secondary: "#fef3c7",
			accent: "#f59e0b",
			background: "#fff7ed",
			foreground: "#78350f",
			destructive: "#dc2626",
			text: "#fff7ed",
		},
	},
	{
		id: "cosmos",
		name: "Cosmos Purple",
		colors: {
			primary: "#5b21b6",
			secondary: "#ede9fe",
			accent: "#8b5cf6",
			background: "#f5f3ff",
			foreground: "#2c0360",
			destructive: "#dc2626",
			text: "#f5f3ff",
		},
	},
];
